name: Docker-compose Actions Workflow - jekyll blog

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        submodules: true
      - name: Install deps
        run: |
          mkdir build
          cd build
          cmake ..
      - name: Build
        run: |
          make
