name: Docker-compose Actions Workflow - jekyll blog

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install system deps
        run: |
          sudo apt-get install \
            libc6-dev-i386 \
            libgl1-mesa-dev libglu1-mesa-dev freeglut3-dev \
            gcc-multilib g++-multilib \
            --fix-missing
      # - name: Install cmake deps
      #   working-directory: ./
      #   run: |
      #     mkdir build
      #     cd build
      #     cmake -DFEATURE_CURL=OFF ..
      - name: Build
        # working-directory: ./
        run: |
          ./easybuild.sh
