name: Docker-compose Actions Workflow - jekyll blog

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install \
            libc6-dev-i386 \
            libgl1-mesa-dev libglu1-mesa-dev freeglut3-dev \
            gcc-multilib g++-multilib \
            libx11-dev xserver-xorg-dev xorg-dev freeglut3-dev libudev-dev \
            nasm
            # --fix-missing

          sudo apt-get install build-essential cmake libjpeg-dev \
            libcurl4-openssl-dev libogg-dev libsdl2-dev \
            libsdl2-2.0.0 libsdl2-dev libglew-dev libjpeg-turbo8 liblua5.1-0-dev libpng-dev
          sudo apt-get install gcc-multilib g++-multilib multiarch-support
      - name: Install cmake deps
        working-directory: ./
        run: |
          mkdir build
          cd build
          cmake -DFEATURE_CURL=OFF ..
      - name: Build
        working-directory: ./build
        run: |
          make
        # run: |
        # ./easybuild.sh
