name: Docker-compose Actions Workflow - jekyll blog

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install system deps
        run: |
          sudo apt-get update
          # sudo apt-get install \
          #   libc6-dev-i386 \
          #   libgl1-mesa-dev libglu1-mesa-dev freeglut3-dev \
          #   gcc-multilib g++-multilib \
          #   libx11-dev xserver-xorg-dev xorg-dev freeglut3-dev libudev-dev \
          #   nasm
          #   # --fix-missing

          # sudo apt-get install build-essential cmake libjpeg-dev \
          #   libcurl4-openssl-dev libogg-dev libsdl2-dev \
          #   libsdl2-dev libglew-dev libjpeg-turbo8 liblua5.1-0-dev libpng-dev
          # sudo apt-get install gcc-multilib g++-multilib multiarch-support
          sudo apt-get install build-essential libfreeimage-dev libopenal-dev libpango1.0-dev \
            libsndfile-dev libudev-dev libasound2-dev libjpeg8-dev libwebp-dev automake libgl1-mesa-glx \
            libjpeg62-turbo libogg0 libopenal1 libvorbis0a libvorbisfile3 zlib1g libraspberrypi0 \
            libraspberrypi-bin libraspberrypi-dev libx11-dev libglew-dev libegl1-mesa-dev \
            nasm autoconf git cmake zip gcc g++ libtool libxrandr-dev x11proto-randr-dev
      - name: Install cmake deps
        working-directory: ./
        run: |
          mkdir build
          cd build
          cmake -DFEATURE_CURL=OFF -D ..
      - name: Build
        working-directory: ./build
        run: |
          make
        # run: |
        # ./easybuild.sh
